### PR TITLE
Remove final

### PR DESCRIPTION
**Pull request by gregurco**
Hello.
I want to use this package in 8p/GuzzleBundle (https://github.com/8p/GuzzleBundle/pull/129) but I can't because in my case Bundle class defines Compiler Pass and I need to do it in build method, but it's final.

### CODE REVIEW

**Comment by gregurco** [comment]
I also fixed the travis configuration. For now php 5.3 is not supported on Trusty image and dist should be changed. Doc: https://docs.travis-ci.com/user/reference/trusty/#PHP-images

**Comment by Spomky** [comment]
There is no need to remove these final keywords.
You just have to register a plugin with a build method that will declare your compiler pass.

It is clearly explained in the documentation: https://github.com/matthiasnoback/symfony-bundle-plugins/blob/master/README.md#register-compiler-passes

**Comment by gregurco** [comment]
In my case, this compiler pass is not optional, it's required. So, do I need to define plugin that will be in the same repository and will be always registered just because there is no need to rewrite **build** method? What's the advantage of keeping there **final**?

**Comment by Spomky** [comment]
Yes.

* Create a plugin with the `build` method that registers your compiler pass
* Override the method `alwaysRegisteredPlugins()` and set your plugin (see last section of the [example](https://github.com/matthiasnoback/symfony-bundle-plugins#example)

Some advantages of the `final` keyword are listed in this [nice blog post](http://ocramius.github.io/blog/when-to-declare-classes-final/).

**Comment by matthiasnoback** [comment]
Thanks for explaining the issue as well as the solution. I introduced
`final` because I wanted this library to be easy to use, without
accidentally making implementation mistakes (like forgetting to call
`parent::build()`). I hope it turns out to be useful for you!

**Comment by gregurco** [comment]
Got it, thanks :+1:

**Comment by matthiasnoback** [comment]
You're welcome!

**Pull request closed without merging**
