### PR TITLE
PrependExtensionInterface interface added

### PR DESCRIPTION
**Pull request by Spomky**
This PR adds PrependExtensionInterface to the class `ExtensionWithPlugins`.
Now plugins that also implement this interface can prepend configuration before the `load` method is called.

This PR is similar to #8, but without BC-Break.
Existing plugins do not have to change anything and will work as expected.
Test included.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks man! Excellent work. It does feel a bit strange to let a bundle plugin implement `PrependExtensionInterface`, but, since that interface is pretty much stand-alone (it has no other methods and doesn't inherit anything), it's okay :)

**Comment by matthiasnoback** [comment]
Tagged `v1.1.0`.

**Comment by Spomky** [comment]
Thanks to you.
Already implemented [into my project](https://github.com/Spomky-Labs/OAuth2ServerBundle/commit/c690443525a1bc0023040d216df1854c53e7ee5e)

**Comment by matthiasnoback** [comment]
Excellent, well done!

**Pull request merged**
