### PR TITLE
[Feature] Add Support Bundle Default Configuration

### PR DESCRIPTION
**Pull request by ad3n**
This PR add support for default configuration and also rename alwaysRegisteredPlugin to defaultPlugins.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
I appreciate the effort but I would've liked to discuss this first. It
deviates pretty much from the way this package currently works. Existing
users may not need that default configuration but now they have to
implement that method. Also I don't think that introducing the cyclic
dependency by passing arround `$this` is a good idea. It requires opening
up the API by making methods public that should have been protected or
private. Finally, tests are missing.

If it works in your situation I would encourage you to maintain your own
fork of this package. There's no problem with that of course! Besides, I
don't think this package will receive many updates so you won't have to do
a lot of backporting.

This PR add support for default configuration and also rename

## alwaysRegisteredPlugin to defaultPlugins.

You can view, comment on, or merge this pull request online at:

  https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7
Commit Summary
- add support for default plugin
- add api doc annotation

File Changes
- _M_ src/BundleWithPlugins.php
  https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7/files#diff-0
  (18)
- _M_ src/ConfigurationWithPlugins.php
  https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7/files#diff-1
  (22)
- _M_ src/ExtensionWithPlugins.php
  https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7/files#diff-2
  (21)

Patch Links:
- https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7.patch
- https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7.diff

—
Reply to this email directly or view it on GitHub
https://github.com/matthiasnoback/symfony-bundle-plugins/pull/7.

**Comment by ad3n** [comment]
First point, i was remove abstract keyword the addConfiguration method, so if user want to add default config, he just need to override the method.

About passing `$this` to Extension class, i don't think we have other option.

And the test is green now :-)

**Comment by magarzon** [comment]
I don't see either the need for a main configuration, when you can have it in a CorePlugin.

If you want something shared between plugins, you can save it in the container, when CorePlugin configuration is loaded.

Maybe if you give us a concrete example of what you think it's 'global' configuration...

**Comment by matthiasnoback** [comment]
@ihsanudin again, I appreciate your effort, but this doesn't really add something that wasn't possible before using a core/main plugin. Also, because of [this PR](https://github.com/matthiasnoback/symfony-bundle-plugins/pull/5) what you want to achieve is doable now for just your own project. I want this library to be as simple/small as possible.

**Comment by matthiasnoback** [comment]
Closing this too, since it won't be added. You can easily start your own project based on this if you like!

**Pull request closed without merging**
